channels:
- conda-forge
dependencies:
- python
- numpy
- openmpi =4.1.6
- cloudpickle =3.1.1
- mpi4py
- pyzmq =27.0.0
- h5py
- networkx =3.4.2
- pygraphviz
- pysqa =0.2.7
- ipython
- hatchling =1.27.0
- hatch-vcs =0.5.0
